### ISSUE TITLE
Raspberry pi ?

### ISSUE THREAD

**Issue by vlidu** [mherrmann/helium#1]
Hey man !

Nice job !
I was wondering if you support ARM devices like raspberry pi ?
I gave a shot but I got a `Exec format error`, and I am assuming linux drivers are not compatible for ARM platform :)

**Comment by teruakohatu** [comment]
The author says in the README that he will not respond to issues.

**Comment by mherrmann** [comment]
Thank you Te. I say I do respond if it's easy for me. It is easy for me to respond to this one: I don't support ARM devices. If you want to submit a Pull Request that adds this @vlidu, feel free to create one.

Closing this :-)

**Comment by pabs3** [comment]
Probably the right way to support ARM and other platforms would be to remove the webdriver binaries from git and require people to download the right one for their platform, possibly providing a script that would help to do that. For example Ubuntu distributes ARM geckodriver [here](https://launchpad.net/ubuntu/focal/arm64/firefox-geckodriver) even though Mozilla [doesn't build ARM binaries any more](https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html).

**Comment by qqgg231** [comment]
Probably fixed by https://github.com/mherrmann/selenium-python-helium/commit/6b970dcf170968ffccb3c833d391b71fa14b8447

**Comment by pabs3** [comment]
This fix means that RPi users have to know that Mozilla doesn't provide
a geckodriver binary for ARM and then find out that Ubuntu does provide
one and then find out where it is, download it and install it.

A better option would be to remove the webdriver binaries from git and
require people to download the right one for their platform by
providing them with a script that would download from Mozilla for most
platforms and from Ubuntu for ARM platforms.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by qqgg231** [comment]
>  A better option would be to remove the webdriver binaries from git

Removing isn't necessary, it won't give any benefit in current state. Helium should use driver on PATH if available.

And by keeping drivers in git, helium is giving easier start to most of new users. What is needed is to add instruction / script / driver for ARM platform

**Comment by pabs3** [comment]
Agreed the current state doesn't allow removing them but the ideal
situation would be that they get removed.

One should always remove binaries and other build products from git
since git is for source code, not build products. Binaries and other
build products should instead be built from source, preferably as often
as possible using CI/CD, stored in packages and installed with a
package manager like conda. With GitHub, the build products can be
attached to releases for manual downloads or imported into GitHub
hosted package repositories for much easier installation.

https://github.com/features/actions
https://github.com/features/packages

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
