### ISSUE TITLE
press method is not working

### ISSUE THREAD

**Issue by akhilkumarco007** [mherrmann/helium#8]
First of all, thank you for such an amazing tool. I really appreciate your time and effort on this project. I wish I could support your work on this. I know you said you won't respond to issues but I just hit a dead end and praying for your help :) 

I am not sure what I doing wrong but whenever I use the press method to enter a combination, nothing happens but the method completes execution. For example, I tried press(CONTROL + SHIFT + 'r') to hard refresh the page and nothing happens. I tried press(CONTROL + 't') for a new tab and nothing happens. I thought it was just my machine and tried it on my friend's machine and got the same thing. 

Once again, thank you so much for your time.

**Comment by mherrmann** [comment]
It seems to me like the things you are trying to do - opening a new tab, reloading the page - are browser shortcuts rather than shortcuts for the web site. I suggest you use JavaScript to accomplish them. In Helium, you can do

    get_driver().execute_script(...)

to execute JavaScript. If you google for "JavaScript reload page" and "JavaScript open tab", then you should be able to achieve what you want.
